// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.22.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> imgcompress(
        {required String path,
        required String outPath,
        required int jpegQuality,
        required int pngQuality,
        required int webpQuality,
        required int gifQuality,
        dynamic hint}) =>
    RustLib.instance.api.imgcompress(
        path: path,
        outPath: outPath,
        jpegQuality: jpegQuality,
        pngQuality: pngQuality,
        webpQuality: webpQuality,
        gifQuality: gifQuality,
        hint: hint);
