
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async openSettingsWindow(path: string | null) : Promise<void> {
    await TAURI_INVOKE("open_settings_window", { path });
},
async openLinkInBrowser(url: string) : Promise<void> {
    await TAURI_INVOKE("open_link_in_browser", { url });
},
async processImg(parameters: ProfileData, file: FileEntry) : Promise<Result<CompressResult, CompressError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("process_img", { parameters, file }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFileInfo(path: string) : Promise<Result<FileInfoResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_info", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAllImages(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_images", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Result<SettingsData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSettings(settings: SettingsData) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetSettings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetProfile(profileId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_profile", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteProfile(profileId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_profile", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addProfile(name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_profile", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openFinderAtPath(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_finder_at_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCpuCount() : Promise<number> {
    return await TAURI_INVOKE("get_cpu_count");
}
}

/** user-defined events **/


export const events = __makeEvents__<{
addFileEvent: AddFileEvent,
badFileEvent: BadFileEvent,
clearFilesEvent: ClearFilesEvent,
openAddFileDialogEvent: OpenAddFileDialogEvent,
settingsChangedEvent: SettingsChangedEvent,
updateStateEvent: UpdateStateEvent
}>({
addFileEvent: "add-file-event",
badFileEvent: "bad-file-event",
clearFilesEvent: "clear-files-event",
openAddFileDialogEvent: "open-add-file-dialog-event",
settingsChangedEvent: "settings-changed-event",
updateStateEvent: "update-state-event"
})

/** user-defined constants **/



/** user-defined types **/

export type AddFileEvent = string
export type BadFileEvent = string
export type ClearFilesEvent = null
export type CompressError = { error: string; errorType: CompressErrorType }
export type CompressErrorType = "Unknown" | "FileTooLarge" | "FileNotFound" | "UnsupportedFileType" | "WontOverwrite" | "NotSmaller"
export type CompressResult = { path: string; outSize: number; outPath: string; result: string }
export type FileEntry = { path: string; file: string | null; status: FileEntryStatus; size: number | null; originalSize: number | null; ext: string | null; savings: number | null; error: string | null }
export type FileEntryStatus = "Processing" | "Compressing" | "Complete" | "AlreadySmaller" | "Error"
export type FileInfoResult = { size: number; extension: string; filename: string }
export type ImageType = "JPEG" | "PNG" | "WEBP" | "GIF" | "TIFF"
export type OpenAddFileDialogEvent = null
export type ProfileData = { name: string; id: number; active: boolean; should_resize: boolean; should_convert: boolean; should_overwrite: boolean; enable_lossy?: boolean; keep_metadata?: boolean; add_posfix?: boolean; convert_extension: ImageType; postfix: string; resize_width: number; resize_height: number; jpeg_quality: number; png_quality: number; webp_quality: number; gif_quality: number }
export type SettingsChangedEvent = null
export type SettingsData = { version: number; theme: ThemeKind; threads?: number; profiles: ProfileData[] }
export type ThemeKind = "Light" | "Dark" | "System"
export type UpdateStateEvent = { type: "CheckingForUpdate"; message: string } | { type: "NoUpdate"; message: string } | { type: "Error"; message: string } | { type: "Downloading"; percent: number; bytes_downloaded: number; total_bytes: number } | { type: "Success"; version: string; release_notes: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
