// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	openSettingsWindow: (path: string | null) => __TAURI_INVOKE<void>("open_settings_window", { path }),
	openLinkInBrowser: (url: string) => __TAURI_INVOKE<void>("open_link_in_browser", { url }),
	processImg: (parameters: ProfileData_Deserialize, file: FileEntry, parallelImages: number) => typedError<CompressResult, AlicError>(__TAURI_INVOKE("process_img", { parameters, file, parallelImages })),
	getFileInfo: (path: string) => typedError<FileInfoResult, string>(__TAURI_INVOKE("get_file_info", { path })),
	getAllImages: (path: string) => typedError<null, string>(__TAURI_INVOKE("get_all_images", { path })),
	getSettings: () => typedError<SettingsResult_Serialize, string>(__TAURI_INVOKE("get_settings")),
	saveSettings: (settings: SettingsData_Deserialize) => typedError<null, string>(__TAURI_INVOKE("save_settings", { settings })),
	resetSettings: () => typedError<null, string>(__TAURI_INVOKE("reset_settings")),
	resetProfile: (profileId: number) => typedError<null, string>(__TAURI_INVOKE("reset_profile", { profileId })),
	deleteProfile: (profileId: number) => typedError<null, string>(__TAURI_INVOKE("delete_profile", { profileId })),
	addProfile: (name: string) => typedError<null, string>(__TAURI_INVOKE("add_profile", { name })),
	openSettingsFolder: () => typedError<null, string>(__TAURI_INVOKE("open_settings_folder")),
	openFinderAtPath: (path: string) => typedError<null, string>(__TAURI_INVOKE("open_finder_at_path", { path })),
	getCpuCount: () => __TAURI_INVOKE<number>("get_cpu_count"),
	getAccentColor: () => typedError<[number, number, number, number], string>(__TAURI_INVOKE("get_accent_color")),
	setDockBadge: (count: number) => __TAURI_INVOKE<void>("set_dock_badge", { count }),
	bounceDockIcon: () => __TAURI_INVOKE<void>("bounce_dock_icon"),
};

/** Events */
export const events = {
	addFileEvent: makeEvent<AddFileEvent>("add-file-event"),
	badFileEvent: makeEvent<BadFileEvent>("bad-file-event"),
	clearFilesEvent: makeEvent<ClearFilesEvent>("clear-files-event"),
	openAddFileDialogEvent: makeEvent<OpenAddFileDialogEvent>("open-add-file-dialog-event"),
	settingsChangedEvent: makeEvent<SettingsChangedEvent>("settings-changed-event"),
	updateStateEvent: makeEvent<UpdateStateEvent>("update-state-event"),
};

/* Types */
export type AddFileEvent = string;

export type AlicError = {
	error: string,
	errorType: AlicErrorType,
};

export type AlicErrorType = "Unknown" | "FileTooLarge" | "FileNotFound" | "UnsupportedFileType" | "WontOverwrite" | "NotSmaller" | "ImageResizeError" | "InvalidHexColor";

export type BadFileEvent = string;

export type ClearFilesEvent = null;

export type CompressResult = {
	path: string,
	outSize: number,
	outPath: string,
	result: string,
};

export type FileEntry = {
	path: string,
	file: string | null,
	status: FileEntryStatus,
	size: number | null,
	originalSize: number | null,
	ext: string | null,
	savings: number | null,
	error: string | null,
};

export type FileEntryStatus = "Processing" | "Compressing" | "Complete" | "AlreadySmaller" | "Error";

export type FileInfoResult = {
	size: number,
	extension: string,
	filename: string,
};

export type ImageType = "JPEG" | "PNG" | "WEBP" | "GIF" | "TIFF" | "AVIF";

export type OpenAddFileDialogEvent = null;

export type ProfileData = ProfileData_Serialize | ProfileData_Deserialize;

export type ProfileData_Deserialize = {
	name?: string,
	id?: number,
	active?: boolean,
	should_resize?: boolean,
	should_convert?: boolean,
	should_overwrite?: boolean,
	enable_lossy?: boolean,
	keep_timestamps?: boolean,
	keep_metadata?: boolean,
	should_background_fill?: boolean,
	background_fill?: string,
	convert_extension?: ImageType,
	postfix?: string,
	resize_width?: number,
	resize_height?: number,
	jpeg_quality?: number,
	png_quality?: number,
	webp_quality?: number,
	gif_quality?: number,
	avif_quality?: number,
} & {
	add_postfix?: boolean,
} | {
	add_posfix?: boolean,
};

export type ProfileData_Serialize = {
	name: string,
	id: number,
	active: boolean,
	should_resize: boolean,
	should_convert: boolean,
	should_overwrite: boolean,
	enable_lossy: boolean,
	keep_timestamps: boolean,
	keep_metadata: boolean,
	add_postfix: boolean,
	should_background_fill: boolean,
	background_fill: string,
	convert_extension: ImageType,
	postfix: string,
	resize_width: number,
	resize_height: number,
	jpeg_quality: number,
	png_quality: number,
	webp_quality: number,
	gif_quality: number,
	avif_quality: number,
};

export type SettingsChangedEvent = null;

export type SettingsData = SettingsData_Serialize | SettingsData_Deserialize;

export type SettingsData_Deserialize = {
	version?: number,
	theme?: ThemeKind,
	threads?: number,
	default_profile_id?: number | null,
	profiles?: ProfileData_Deserialize[],
};

export type SettingsData_Serialize = {
	version: number,
	theme: ThemeKind,
	threads: number,
	default_profile_id: number | null,
	profiles: ProfileData_Serialize[],
};

export type SettingsResult = SettingsResult_Serialize | SettingsResult_Deserialize;

export type SettingsResult_Deserialize = {
	settings: SettingsData_Deserialize,
	warning: string | null,
};

export type SettingsResult_Serialize = {
	settings: SettingsData_Serialize,
	warning: string | null,
};

export type ThemeKind = "Light" | "Dark" | "System";

export type UpdateStateEvent = { type: "CheckingForUpdate"; message: string } | { type: "NoUpdate"; message: string } | { type: "Error"; message: string } | { type: "Downloading"; percent: number | null; bytes_downloaded: number | null; total_bytes: number | null } | { type: "Success"; version: string; release_notes: string | null };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

